In [11]:
#这是一个numpy和pandas的复习记录
#axis=0 是按跨行的方向
#axis=1 是按跨列的方向

In [1]:
#1.矩阵的元素
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
#矩阵的维度
print(arr.ndim)
#矩阵的形状，返回（行数，列数）
print(arr.shape)
#矩阵内部元素个数
print(arr.size)

2
(2, 3)
6


In [22]:
#指定数据类型创建数组
arr2 = np.array([1,2,3],dtype=np.float32)
print(arr2)
print(arr2.dtype)

[1. 2. 3.]
float32


In [23]:
#创建全0或者全1的数组
arr3 = np.zeros((3,4))
arr4 = np.ones((3,4))
print(arr3)
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
#创建全空的数组
arr5 = np.empty((3,4))
print(arr5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [48]:
#连续创建数组(实际创建的是从开始到结束-1的固定步长的数组)
#（起始，结束，步长）
arr6 = np.arange(10,20,1)
print(arr6)

[10 11 12 13 14 15 16 17 18 19]


In [49]:
#改变数组的形状
print(arr6.reshape(2,5))
print(arr6.reshape(2,5).mean(axis=1))

[[10 11 12 13 14]
 [15 16 17 18 19]]
[12. 17.]


In [34]:
#创造线段型的数据(起始，结束，平均分的点数),类似于平均采样
arr7 = np.linspace(1,10,10)
print(arr7)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
#nummpy基础运算
a = np.arange(6
b = np.linspace(1,5,6)
print(a + b,a * b)

[ 1.   2.8  4.6  6.4  8.2 10. ] [ 0.   1.8  5.2 10.2 16.8 25. ]


In [39]:
#也可以使用如下的语句对元素进行判断
print(a>3)

[False False False False  True  True]


In [42]:
#行列不匹配时的加法
d = np.arange(3)
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c + d)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [4 6 8]]


In [44]:
#矩阵乘法 dot
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[1],[3]])
print(np.dot(matrix1, matrix2))
print(matrix1.dot(matrix2))

[[ 7]
 [15]]
[[ 7]
 [15]]


In [59]:
#初始化特定大小的随机数（0-1）的矩阵
matrix3 = np.random.random((2,3))
print(matrix3)

[[0.96164647 0.94176442 0.90261903]
 [0.95487013 0.82170021 0.26623195]]


In [62]:
matrix4 = np.array([[1,0,3],[4,0,6]])
print(matrix4) 
print(np.sum(matrix4))
print(matrix4.sum())
print(np.median(matrix4))
#累和运算 
print(np.cumsum(matrix4))
#累差运算,2*3的矩阵就会变为2*2 
print(np.diff(matrix4))

[[1 0 3]
 [4 0 6]]
14
14
2.0
[ 1  1  4  8  8 14]
[[-1  3]
 [-4  6]]


In [63]:
#nonzero()函数，这个函数将所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵
print(np.nonzero(matrix4))
a1,a2 = np.nonzero(matrix4)
print(a1)#非0行
print(a2)#非0列

(array([0, 0, 1, 1], dtype=int64), array([0, 2, 0, 2], dtype=int64))
[0 0 1 1]
[0 2 0 2]


In [3]:
#clip函数，（目标矩阵，小于该数字的替换成该数，小于该数字的替换成该数）
matrix7 = np.array([[1,2,3,5],[5,8,9,7]])
print(matrix7)
print(np.clip(matrix7, 6, 7))

[[1 2 3 5]
 [5 8 9 7]]
[[6 6 6 6]
 [6 7 7 7]]


In [10]:
#矩阵的索引
matrix8 = np.array([[1,2,3,5],[5,8,9,7]])
print(matrix8[0,:])
print(matrix8[0][0])
print(matrix8[0,0])

#打印出矩阵的每一行
for _ in matrix8:
    print(_)
#打印出矩阵的每一列
for _ in matrix8.T:
    print(_) 
#打印出矩阵的每一个元素
#flatten方法将矩阵变为一维的
# .flat是一个迭代器属性
print(matrix8.flat)
for _ in matrix8.flatten():
    print(_) 
for _ in matrix8.flat:
    print(_) 

[1 2 3 5]
1
1
[1 2 3 5]
[5 8 9 7]
[1 5]
[2 8]
[3 9]
[5 7]
1
2
3
5
5
8
9
7
1
2
3
5
5
8
9
7


In [23]:
#矩阵的合并
A = np.array([[1,1,1]])
B = np.array([[2,2,2]])
C = np.array([[3,3,3]])
#上下合并,vstack以元组的形式传参
print(np.vstack((A,B)))
#左右合并,vstack以元组的形式传参
print(np.hstack((A,B)))
#多个数组合并np.concatenate()
print(np.concatenate((A,B),axis=0))
print(np.concatenate((A,B),axis=1))

[[1 1 1]
 [2 2 2]]
[[1 1 1 2 2 2]]
[[1 1 1]
 [2 2 2]]
[[1 1 1 2 2 2]]


In [32]:
#矩阵的分割
matrix9 = np.arange(12).reshape((3,4))
print(matrix9)
#纵向分割
print(np.split(matrix9, 2,axis=1))
##不等量的分割
print(np.array_split(matrix9, 3,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
